# eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://${EUREKA_HOST:localhost}:${EUREKA_PORT:10000}/eureka/}
  instance:
    prefer-ip-address: true
    hostname: localhost

logging:
  level:
    com.corsair: debug
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 12345678
