server:
  port: 9981
  http2:
    enabled: true
#  servlet:
#    context-path: /api

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
  response:
    enabled: true
spring:
  profiles:
    active: dev
    include:
      - swagger
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#          route-id-prefix: /api
          lower-case-service-id: true
#        routes:
#        #################################
#        - id: sparrow-pirate-alpha
#          uri: lb://sparrow-pirate-alpha
##          order: 8088
#          predicates:
#          - Path=/alpha/**
#          filters:
#          - StripPrefix=2   # 跳过几个路由前缀
#          - name: Retry
#            args:
#              retries: 3 # 重试次数，默认3，不包含本次
#              status: 404 # 重试response code,默认没有
#              statusSeries: 500 # 重试response code : 100(info),200(success),300(redirect),400(client error),500(server error),默认500
#              method: GET # 重试的request请求，默认GET

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetiesNextServer: 1
  OkToRetryOnAllOperations: false

# hystrix 设置
hystrix:
  threadpool:
    default:
      ## 并发最大线程数，默认10
      coreSize: 1000
      ## BlockingQueue的最大队列数
      maxQueueSize: 1000
      ## 即使maxQueueSize没有达到，达到queueSizeRejectionThreshold值后，请求也会被拒绝
      queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

